-- MySQL 8.0+, apply once to an empty database. All dates are UTC.
SET time_zone = '+00:00';
CREATE TABLE SeedVersions (Version VARCHAR(100) PRIMARY KEY);
CREATE TABLE Users (
 Id BIGINT PRIMARY KEY AUTO_INCREMENT,
 GoogleSubjectId VARCHAR(255) NULL UNIQUE,
 Email VARCHAR(320) NOT NULL, DisplayName VARCHAR(200) NOT NULL,
 AvatarUrl VARCHAR(2048) NULL,
 CreatedAt DATETIME(6) NOT NULL DEFAULT (UTC_TIMESTAMP(6)),
 LastLoginAt DATETIME(6) NOT NULL DEFAULT (UTC_TIMESTAMP(6))
);
CREATE TABLE Products (
 Id BIGINT PRIMARY KEY AUTO_INCREMENT,
 Symbol VARCHAR(32) NOT NULL, Name VARCHAR(200) NOT NULL,
 Market VARCHAR(32) NOT NULL, AssetType VARCHAR(32) NOT NULL,
 IsLeveraged BOOLEAN NOT NULL DEFAULT FALSE,
 QuantityUnit VARCHAR(16) NOT NULL, UnitSize INT NOT NULL DEFAULT 1,
 IsActive BOOLEAN NOT NULL DEFAULT TRUE,
 CreatedAt DATETIME(6) NOT NULL DEFAULT (UTC_TIMESTAMP(6)),
 UpdatedAt DATETIME(6) NOT NULL DEFAULT (UTC_TIMESTAMP(6)),
 UNIQUE KEY UQ_Product(Market,Symbol), CHECK(UnitSize>0)
);
CREATE TABLE UserWatchlists (
 Id BIGINT PRIMARY KEY AUTO_INCREMENT,
 UserId BIGINT NOT NULL, ProductId BIGINT NOT NULL,
 CreatedAt DATETIME(6) NOT NULL DEFAULT (UTC_TIMESTAMP(6)),
 UNIQUE KEY UQ_Watch(UserId,ProductId),
 FOREIGN KEY(UserId) REFERENCES Users(Id), FOREIGN KEY(ProductId) REFERENCES Products(Id)
);
CREATE TABLE UserPositions (
 Id BIGINT PRIMARY KEY AUTO_INCREMENT,
 UserId BIGINT NOT NULL, ProductId BIGINT NOT NULL,
 Quantity DECIMAL(18,6) NOT NULL, AverageCost DECIMAL(18,6) NOT NULL,
 UpdatedAt DATETIME(6) NOT NULL DEFAULT (UTC_TIMESTAMP(6)),
 UNIQUE KEY UQ_Position(UserId,ProductId),
 FOREIGN KEY(UserId) REFERENCES Users(Id), FOREIGN KEY(ProductId) REFERENCES Products(Id),
 CHECK(Quantity>=0), CHECK(AverageCost>=0)
);
CREATE TABLE AIProviders (
 Id BIGINT PRIMARY KEY AUTO_INCREMENT,
 Code VARCHAR(32) NOT NULL UNIQUE, DisplayName VARCHAR(100) NOT NULL,
 IsEnabled BOOLEAN NOT NULL DEFAULT TRUE, SortOrder INT NOT NULL DEFAULT 0
);
CREATE TABLE AIAnalysisResults (
 Id BIGINT PRIMARY KEY AUTO_INCREMENT,
 UserId BIGINT NOT NULL, ProductId BIGINT NOT NULL, AIProviderId BIGINT NOT NULL,
 Model VARCHAR(100) NOT NULL,
 Action ENUM('ADD','HOLD','REDUCE','EXIT') NOT NULL, Quantity DECIMAL(18,6) NULL,
 Confidence INT NOT NULL, AnalysisJson JSON NOT NULL, InputSnapshotJson JSON NOT NULL,
 RawResponse LONGTEXT NOT NULL,
 CreatedAt DATETIME(6) NOT NULL DEFAULT (UTC_TIMESTAMP(6)),
 FOREIGN KEY(UserId) REFERENCES Users(Id), FOREIGN KEY(ProductId) REFERENCES Products(Id),
 FOREIGN KEY(AIProviderId) REFERENCES AIProviders(Id),
 INDEX IX_AnalysisHistory(UserId,ProductId,AIProviderId,CreatedAt DESC,Id DESC),
 CHECK(Confidence BETWEEN 0 AND 100), CHECK(Quantity IS NULL OR Quantity>0),
 CHECK(Action IN ('ADD','REDUCE') OR Quantity IS NULL)
);
