CREATE TABLE IF NOT EXISTS AnalysisScheduleSettings (
 UserId BIGINT PRIMARY KEY, Enabled BOOLEAN NOT NULL, TimesJson JSON NOT NULL,
 FOREIGN KEY (UserId) REFERENCES Users(Id)
);
CREATE TABLE IF NOT EXISTS AnalysisScheduleClaims (
 UserId BIGINT NOT NULL, TradeDate DATE NOT NULL, MinuteOfDay INT NOT NULL,
 ClaimedAt DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
 PRIMARY KEY (UserId, TradeDate, MinuteOfDay), FOREIGN KEY (UserId) REFERENCES Users(Id)
);
