CREATE TABLE IF NOT EXISTS NewsContexts (
 Id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
 WindowStart DATETIME(6) NOT NULL, WindowEnd DATETIME(6) NOT NULL, GeneratedAt DATETIME(6) NOT NULL,
 SearchProvider VARCHAR(64) NOT NULL, CollectorProvider VARCHAR(64) NOT NULL,
 ConfiguredModel VARCHAR(100) NOT NULL, ActualModel VARCHAR(100) NOT NULL, Status VARCHAR(32) NOT NULL,
 SearchResultCount INT NOT NULL, FilteredResultCount INT NOT NULL, EventCount INT NOT NULL,
 InputTokens BIGINT NULL, OutputTokens BIGINT NULL, CachedTokens BIGINT NULL,
 PromptVersion VARCHAR(100) NOT NULL, ContextJson JSON NOT NULL,
 RawSearchSnapshotJson JSON NOT NULL, NormalizedInputJson JSON NOT NULL,
 PromptSnapshot LONGTEXT NOT NULL, SchemaSnapshot JSON NOT NULL, RawCollectorResponse LONGTEXT NOT NULL,
 INDEX IX_NewsContexts_GeneratedAt (GeneratedAt)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS NewsEvents (
 Id CHAR(32) NOT NULL PRIMARY KEY, NewsContextId BIGINT NOT NULL,
 Category VARCHAR(32) NOT NULL, Title VARCHAR(300) NOT NULL, Summary TEXT NOT NULL,
 EventTime DATETIME(6) NULL, PublishedAt DATETIME(6) NOT NULL,
 Direction VARCHAR(32) NOT NULL, Importance VARCHAR(32) NOT NULL,
 Relevance INT NOT NULL, Confidence INT NOT NULL, TimeQuality VARCHAR(32) NOT NULL,
 EventTimeEvidence TEXT NULL,
 FOREIGN KEY (NewsContextId) REFERENCES NewsContexts(Id), INDEX IX_NewsEvents_Context (NewsContextId)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS NewsEventSources (
 Id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, NewsEventId CHAR(32) NOT NULL,
 ResultId VARCHAR(64) NOT NULL, Publisher VARCHAR(200) NOT NULL, Url TEXT NOT NULL,
 PublishedAt DATETIME(6) NOT NULL, SourceType VARCHAR(64) NOT NULL,
 FOREIGN KEY (NewsEventId) REFERENCES NewsEvents(Id), INDEX IX_NewsEventSources_Event (NewsEventId)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS NewsRefreshFailures (
 Id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
 WindowStart DATETIME(6) NOT NULL, WindowEnd DATETIME(6) NOT NULL, FailedAt DATETIME(6) NOT NULL,
 Stage VARCHAR(32) NOT NULL, Error TEXT NOT NULL, Model VARCHAR(100) NULL,
 InputTokens BIGINT NULL, OutputTokens BIGINT NULL, CachedTokens BIGINT NULL, RawCollectorResponse LONGTEXT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
